import turtle as t
t.speed(10)
t.shape('turtle')
t.bgcolor('black')

start=input('start')
if start=='start':

    t.penup()
    t.goto(-360,240)
    t.pendown()
    t.color('white')
    t.begin_fill()
    t.forward(720)
    t.right(90)
    t.forward(480)
    t.right(90)
    t.forward(720)
    t.right(90)
    t.forward(480)
    t.right(90)
    t.end_fill()

    t.goto(0,-120)
    t.circle(120,54)

    t.color('firebrick')
    t.begin_fill()
    t.begin_fill()
    t.circle(120,180)
    t.end_fill()

    t.color('navy')
    t.begin_fill()
    t.begin_fill()
    t.circle(120,180)
    t.end_fill()

    t.begin_fill()
    t.circle(60,180)
    t.end_fill()

    t.color('firebrick')
    t.right(180)
    t.begin_fill()
    t.circle(60,-180)
    t.end_fill()

    t.penup()
    t.color('black')
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(60)
    t.left(90)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.right(180)
    t.forward(30)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(120)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.right(180)
    t.forward(30)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.goto(0,0)
    t.right(108)
    t.forward(180)
    t.right(90)
    t.forward(60)
    t.left(90)

    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.right(180)
    t.forward(30)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.left(90)
    t.forward(10)
    t.left(90)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.right(180)
    t.forward(30)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.forward(440)
    t.right(180)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.left(90)
    t.forward(10)
    t.left(90)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.forward(10)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(120)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.left(180)
    t.forward(30)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.left(90)
    t.forward(55)
    t.left(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.right(90)
    t.forward(10)
    t.right(90)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.left(90)
    t.forward(55)
    t.left(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.goto(0,0)
    t.left(108)
    t.forward(180)
    t.left(90)
    t.forward(60)

    t.right(90)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.left(90)
    t.forward(10)
    t.pendown()
    t.begin_fill()
    t.forward(55)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(55)
    t.end_fill()
    t.penup()

    t.forward(65)
    t.right(90)
    t.forward(10)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.left(90)
    t.forward(10)
    t.pendown()
    t.begin_fill()
    t.forward(55)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(55)
    t.end_fill()
    t.penup()

    t.forward(65)
    t.right(90)
    t.forward(10)
    t.pendown()
    t.begin_fill()
    t.forward(20)
    t.right(90)
    t.forward(55)
    t.right(90)
    t.forward(20)
    t.end_fill()
    t.penup()

    t.left(90)
    t.forward(10)
    t.pendown()
    t.begin_fill()
    t.forward(55)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(55)
    t.end_fill()
    t.penup()

    t.hideturtle()

    t.mainloop()